name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout el código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Ejecutar pruebas
      - name: Run tests
        run: npm test

      # Construir la aplicación
      - name: Build application
        run: npm run build
